WebUniversity/Models/GroupStudents.cs
using DBModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUniversity.Models
{
    public class GroupStudents
    {
        public IEnumerable<Group> Groups { get; set; }
        public IEnumerable<Student> Students { get; set; }
    }
}

WebUniversity/Models/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebUniversity.Models
{
    public class Login
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        //[Display(Name = "Remember me?")]
        //public bool RememberMe { get; set; }
    }
}

WebUniversity/Models/StudentModelView.cs
using DBModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUniversity.Models
{
    public class StudentModelView
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public int GroupId { get; set; }
        public IEnumerable<Group> Groups { get; set; }

        public StudentModelView() { }
        public StudentModelView(Student student)
        {
            Id = student.Id;
            FirstName = student.FirstName;
            LastName = student.LastName;
            Age = student.Age;
            GroupId = student.GroupId;
        }
    }
}

WebUniversity/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUniversity.Models;

namespace WebUniversity.Controllers
{
    public class AccountController : Controller
    {
        //
        // GET: /Action/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View(new Login());
        }
	}
}

WebUniversity/Controllers/GroupController.cs
using BLL.Implementations;
using BLL.Interfaces;
using DAL;
using DBModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUniversity.Controllers
{
    public class GroupController : Controller
    {
        public IGroupManager mngr;
        //
        public GroupController(IGroupManager mngr)
        {
            this.mngr = mngr;
            //mngr = new GroupManager(new UnitOfWork());
        }

        // GET: /Group/
        public ActionResult Index()
        {
            var groups = mngr.GetGroups();
            return View(groups);
        }

        public ActionResult Delete(int id)
        {
            var group = mngr.GetGroupById(id);
            mngr.DeleteGroup(group);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AddGroup()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddGroup(Group group)
        {
            mngr.AddGroup(group);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var group = mngr.GetGroupById(id);
            return View(group);
        }

        [HttpPost]
        public ActionResult Edit(Group group)
        {
            //var group = mngr.GetGroupById(id);
            mngr.EditGroup(group);
            return RedirectToAction("Index");
        }
    }
}

WebUniversity/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUniversity.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebUniversity/Controllers/StudentController.cs
using BLL.Interfaces;
using BLL.Implementations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DAL;
using DBModel;
using WebUniversity.Models;

namespace WebUniversity.Controllers
{
    public class StudentController : Controller
    {
        public IStudentManager mngr;
        public IGroupManager grMngr;

        public StudentController(IStudentManager mngr, IGroupManager grMngr)
        {
            this.mngr = mngr;
            this.grMngr = grMngr;
            //mngr = new StudentManager(new UnitOfWork());
        }

        //
        // GET: /Student/
        public ActionResult Index()
        {
            GroupStudents grStudents = new GroupStudents();
            grStudents.Students = mngr.GetStudents();
            grStudents.Groups = grMngr.GetGroups();
            grMngr.GetGroups().Last();
            var students = mngr.GetStudents();
            return View(grStudents);
        }

        public ActionResult Delete(int id)
        {
            var groups = mngr.GetStudentById(id);
            mngr.DeleteStudent(groups);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var groupsMngr = new GroupManager(new UnitOfWork());
            var student = mngr.GetStudentById(id);
            var studModel = new StudentModelView(student);
            studModel.Groups = groupsMngr.GetGroups();
            return View(studModel);
        }

        [HttpPost]
        public ActionResult Edit(Student student)
        {
            //var group = mngr.GetGroupById(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Add()
        {
            var groupsMan = new GroupManager(new UnitOfWork());
            StudentModelView student = new StudentModelView();
            student.Groups = groupsMan.GetGroups();
            return View(student);
        }

        [HttpPost]
        public ActionResult Add(Student student)
        {
            mngr.AddStudent(student);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult AjaxAdd(Student student)
        {
            mngr.AddStudent(student);
            var model = mngr.GetStudents();//.Last();
            return Json(model);
        }

        public ActionResult AjaxAddForm()
        {
            var groupsMan = new GroupManager(new UnitOfWork());
            return Json(groupsMan.GetGroups());
        }
    }
}

WebUniversity/Views/Group/AddGroup.cshtml
@model DBModel.Group

@using (Html.BeginForm("AddGroup", "Group"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebUniversity/Views/Group/Edit.cshtml
@model DBModel.Group

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, @Model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebUniversity/Views/Group/Index.cshtml
@model IEnumerable<DBModel.Group>

<div class="items">
    <h1>Groups</h1>
        <ul class="list formattedList">
            @foreach (var group in Model)
            {
                <li style="width: 100%">
                    <span style="width:50%">@group.Name</span>
                    <div style="float: right">
                        <span>@Html.ActionLink("Edit", "Edit", new { id = @group.Id })</span>
                        &nbsp;
                        <span>@Html.ActionLink("Delete", "Delete", new { id = @group.Id })</span>
                    </div>
                    <div style="clear: both"></div>
                    <input type="hidden" value="@group.Id" />
                </li>
            }
        </ul>
    <uul style="visibility: hidden;">
        <li>werty</li>
    </uul>
    <input type="button" value="New group" id="New" />
    @Html.ActionLink("New", "Add")</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("ul.formattedList li:odd").addClass("oddItem");
        $("ul.formattedList li:even").addClass("evenItem");
        /*$("#New").click(function () {
            console.log($("uul").is("visible"));
            if ($("uul").css('visibility') != 'visible') {
                $("uul").css('visibility', 'visible');
                console.log($("uul").css('visibility'));
            }
        });

        /*$(".btn-add").click(function () {
            console.log("sdgf");
            $.ajax({
                type: "POST",
                url: "/Group/AjaxAdd",
                data: { FirstName: $("#FirstName").val(), LastName: $("#LastName").val(), Age: $("#Age").val(), GroupId: $("#GroupId").val() }
            }).done(function (data) {
                $(".items .list").empty();
                $.each(data, function (i, item) {
                    var li = $('<li>').append(
                        $('<span>').text(item.FirstName), "\n\r",
                        $('<span>').text(item.LastName), "\n\r",
                        $('<span>').text(item.Age), "\n\r",
                        $('<span>').text(item.GroupId), "\n\r",
                        $('<div style="float: right">').html('<a href="/Student/Edit/' + item.Id + '">Edit</a> | ' +
                        '<a href="/Student/Delete/' + item.Id + '">Delete</a>')
                    );
                    console.log("fuq!!");
                    $('.items ul').append(li);
                });
            });
        });*/
    });
</script>

WebUniversity/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebUniversity/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebUniversity/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebUniversity/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/manually.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("University", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "About", "Home")</li>
                    <li>@Html.ActionLink("Groups", "Index", "Group")</li>
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                    <li>@Html.ActionLink("About", "Index", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebUniversity/Views/Student/Add.cshtml
@model WebUniversity.Models.StudentModelView

@using (Html.BeginForm("Add", "Student"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>New Student</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="GroupId" name="GroupId">
                    @foreach (var group in Model.Groups)
                    {
                    <option value="@group.Id">@group.Name</option>                        
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebUniversity/Views/Student/AddStudent.cshtml
@model WebUniversity.Models.StudentModelView

@using (Html.BeginForm("AddStudent", "Student"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>New Student</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="GroupId" name="GroupId">
                    @foreach (var group in Model.Groups)
                    {
                    <option value="@group.Id">@group.Name</option>                        
                    }
                </select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WebUniversity/Views/Student/Edit.cshtml
@model WebUniversity.Models.StudentModelView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StudentModelView</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age)
                @Html.ValidationMessageFor(model => model.Age)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="GroupId" name="GroupId">
                    @foreach (var group in Model.Groups)
                    {
                        if(Model.GroupId == group.Id) 
                        {  
                            <option value="@group.Id" selected>@group.Name</option>
                        }
                        else 
                        { 
                            <option value="@group.Id" >@group.Name</option>
                        }
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebUniversity/Views/Student/Index.cshtml
@model WebUniversity.Models.GroupStudents

<h1>Students</h1>
<div class="items">
    <ul class="list formattedList">
        @if (Model != null)
        {
            foreach (var student in Model.Students)
            {
                <li>
                    <span>@student.FirstName</span>
                    <span>@student.LastName</span>
                    <span>@student.Age</span>
                    <span>@student.GroupId</span>
                    <div style="float: right">
                        <span>@Html.ActionLink("Edit", "Edit", new { id = @student.Id })</span>
                        &nbsp;
                        <span>@Html.ActionLink("Delete", "Delete", new { id = @student.Id })</span>
                    </div>
                    <div style="clear: both"></div>
                </li>
            }
        }
    </ul>
    <uul style="visibility: hidden;">
        <li>
            <input class="text-box single-line" id="FirstName" name="FirstName" type="text" value="" />
            <input class="text-box single-line" id="LastName" name="LastName" type="text" value="" />
            <input class="text-box single-line" data-val="true" data-val-number="The field Age must be a number." data-val-required="The Age field is required." id="Age" name="Age" type="number" value="0" />
            <select id="GroupId" name="GroupId">
                @foreach (var group in Model.Groups)
                {
                    <option value="@group.Id">@group.Name</option>
                }
            </select>
            <input type="button" value="Create" class="btn btn-default btn-add" />
        </li>
    </uul>
<input type="button" value="New student" id="New" />
@Html.ActionLink("New", "Add")
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("ul.formattedList li:odd").addClass("oddItem");
        $("ul.formattedList li:even").addClass("evenItem");
        $("#New").click(function () {
            console.log($("uul").is("visible"));
            if ($("uul").css('visibility') != 'visible') {
                $("uul").css('visibility', 'visible');
                console.log($("uul").css('visibility'));
            }
        });

        $(".btn-add").click(function () {
            console.log("sdgf");
            $.ajax({
                type: "POST",
                url: "/Student/AjaxAdd",
                data: { FirstName: $("#FirstName").val(), LastName: $("#LastName").val(), Age: $("#Age").val(), GroupId: $("#GroupId").val() }
            }).done(function (data) {
                $(".items .list").empty();
                $.each(data, function (i, item) {
                    var li = $('<li>').append(
                        $('<span>').text(item.FirstName), "\n\r",
                        $('<span>').text(item.LastName), "\n\r",
                        $('<span>').text(item.Age), "\n\r",
                        $('<span>').text(item.GroupId), "\n\r",
                        $('<div style="float: right">').html('<a href="/Student/Edit/' + item.Id + '">Edit</a> | ' +
                        '<a href="/Student/Delete/' + item.Id + '">Delete</a>')
                    );
                    console.log("fuq!!");
                    $('.items ul').append(li);
                });
            });
        });
    });

    function liItem() {
        var string = "<li class=\"add-form\">";
        string += '<form>';
        string += '<input class="text-box single-line" id="FirstName" name="FirstName" type="text" value="" />';
        string += '<input class="text-box single-line" id="LastName" name="LastName" type="text" value="" />';
        string += '<input class="text-box single-line" data-val="true" data-val-number="The field Age must be a number." data-val-required="The Age field is required." id="Age" name="Age" type="number" value="0" />';
        string += '<select id="GroupId" name="GroupId">';
        string += '<option value="3">101</option>                        ';
        string += '<option value="4">102</option>                        ';
        string += '<option value="5">502M</option>                        ';
        string += '<option value="6">501C</option>                        ';
        string += '</select>';
        string += '<div style="float: right">';
        string += '<input type="button" value="Create" class="btn btn-default btn-add"/>';
        string += '</div>';
        string += '</form></li>';

        return string;
    }

    function li() {
        var string = "<li>";
        string += "<span>firstName</span>";
        string += "<span>lastName</span>";
        string += "<span>age</span>";
        string += "<span>student.GroupId</span>";
        string += '<div style="float: right">';
        string += "<span></span>";
        string += "&nbsp;";
        string += "<span></span>";
        string += "</div>";

        string += '</li>';
        return string;
        var rec = $('<li>');
    }


</script>